stages:
  - lint
  - test
  - signature-check

lint:
  stage: lint
  image: debian
  before_script:
    - apt-get update -qq
    - apt-get install -qq shellcheck make
  script:
    - make lint

test:
  image: debian
  before_script:
    - apt-get update -qq
    - apt-get install -qq make bats git gnupg2
  script:
    - make test

signature-check:
  stage: signature-check
  image: debian
  before_script:
    - apt-get update -qq
    - apt-get install -qq make git gnupg2
  script:
    - make install prefix=/usr/local
    - git branch
    - git signatures pull
    - git signatures import
    - git signatures show
    - git signatures verify --min-count=2
