before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats git gnupg2 shellcheck
script:
  - alias gpg="/usr/bin/gpg2"
  - gpg --version
  - make test
