before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats git gnupg2 shellcheck
script:
  - make lint
  - make test
  - make install
  - git branch
  - git signatures pull
  - git signatures import
  - git signatures show
  - git signatures verify --min-count=2
